check process filebrowser matching "/mnt/HD/HD_a2/Nas_Prog/filebrowser/filebrowser -d"
	start program = "/bin/sh /mnt/HD/HD_a2/Nas_Prog/filebrowser/start.sh /mnt/HD/HD_a2/Nas_Prog/filebrowser" with timeout 30 seconds
	stop program  = "/bin/sh /mnt/HD/HD_a2/Nas_Prog/filebrowser/stop.sh /mnt/HD/HD_a2/Nas_Prog/filebrowser"
	mode active
